workflows:
  android-workflow:
    name: Android Build, Test & APK Generation Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_VERSION: "17"
      node: latest
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build and Lint check
        script: | 
          chmod +x gradlew
          ./gradlew lintRelease
          ./gradlew assembleDebug --dry-run
      - name: Run Unit Tests
        script: | 
          ./gradlew testReleaseUnitTest
      - name: Build Android Release APK
        script: | 
          ./gradlew assembleRelease
    artifacts: # Guardar los archivos APK (y AAB) generados como artefactos, de esta manera los podemos descargar
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/bundle/**/*.aab
      - app/build/reports/tests/**
    publishing:
      email:
        recipients:
          - javierpulido73@gmail.com
        notify:
          success: true
          failure: true
